### PR TITLE
change index structure to make product easy

### PR DESCRIPTION
**Pull request by PirateCode-eth**
@0xtiby try to make a new structure index to connecting web3 people by onchain data.

### CODE REVIEW

**Comment by PirateCode-eth** [comment]
easy step should have a check at the right of the button after connecting wallet with onchain data detection, but I need to learn more about react to do that lol.

**Comment by 0xtiby** [comment]
Ok I see your point, I like the idea but can I try to make it looks better first ?

**Comment by PirateCode-eth** [comment]
For sure.

**Comment by PirateCode-eth** [comment]
I will close this one.

**Pull request closed without merging**
