### PR TITLE
Proposal on step by step

### PR DESCRIPTION
**Pull request by 0xtiby**

### CODE REVIEW

**Comment by 0xtiby** [comment]
@PirateCode-eth  I let you check and update locales if you want to add better description/ instructions. 
I don't how to check the user has done the step 4.

**Comment by PirateCode-eth** [comment]
looks like there are some conflicts.

**Comment by PirateCode-eth** [comment]
> @PirateCode-eth I let you check and update locales if you want to add better description/ instructions. I don't how to check the user has done the step 4.

for step4, users don't need to do anything, they just goes to the pages that we query the whole community members that set primary PFPs and show their profiles, their twitter accounts, mirror links etc.

**Review by PirateCode-eth — COMMENTED** [review]
LGTM

**Review by PirateCode-eth — APPROVED** [review]

**Review by PirateCode-eth — APPROVED** [review]

**Comment by PirateCode-eth** [comment]
@0xtiby looks like after this upgrade, my primary ENS set in testnet is not detected anymore?

**Comment by 0xtiby** [comment]
@PirateCode-eth  I just pulled the code merged on main and it's working on my side. Did you try before the merge ?  Because on my side while building this I encounter issues with my ENS on testnet too.

**Comment by PirateCode-eth** [comment]
The conflicts are fixed before I merged it, but I am not sure if I fixed it
right, you can double check it :)

**Pull request merged**
